name: CharField
version: 0.2
description: Textfield with visual feedback for length
url: https://github.com/subpixel-ch/statamic-charfield
developer: Rémy Böhler
developer_url: https://subpixel.ch

fieldtype_fields:
  input_type:
    type: select
    options:
      input: Input
      textarea: Textarea
  low:
    type: text
  high:
    type: text
  optimal_min:
    type: text
  optimal_max:
    type: text
  hard_limit:
    type: text
