name: Mousetrap
version: 1.1
description: "Go directly to the content in the CP to edit it"
url: https://github.com/edalzell/statamic-mousetrap
developer: Erin Dalzell
developer_url: https://github.com/edalzell
